/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibal_yazid_saad.View;

import bibal_yazid_saad.Connection.DbInteraction;
import bibal_yazid_saad.Controller.EmpruntControler;
import bibal_yazid_saad.Controller.ExemplaireControler;
import bibal_yazid_saad.Controller.OeuvreControler;
import bibal_yazid_saad.Controller.ReservationControler;
import bibal_yazid_saad.Controller.UsagerControler;
import bibal_yazid_saad.DAO.EmpruntManager;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author dizay
 */
public class IHMemprunt extends javax.swing.JFrame {

    /**
     * Creates new form IHMusager
     */
    OeuvreControler  oc=new OeuvreControler(); 
    ExemplaireControler ec=new ExemplaireControler();
    UsagerControler uc=new UsagerControler();
    ReservationControler rc=new ReservationControler();
    EmpruntControler pc=new EmpruntControler();
       
    public IHMemprunt() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        empruntid = new javax.swing.JTextField();
        emprunter = new javax.swing.JButton();
        vd = new javax.swing.JButton();
        Blist12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        exmpid = new javax.swing.JTextField();
        vidertableau = new javax.swing.JButton();
        chemp = new javax.swing.JButton();
        rendreemp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        usID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cherID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dateempr = new com.toedter.calendar.JDateChooser();
        dateempprev = new com.toedter.calendar.JDateChooser();
        datereche = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        date1 = new com.toedter.calendar.JDateChooser();
        chempintervale = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateretour = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableEmprunt = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        NomForSearch = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboeuvre = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableExemplaire2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        NomForSearch4 = new javax.swing.JLabel();
        Nomrech = new javax.swing.JTextField();
        Blist4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableUsager = new javax.swing.JTable();
        Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Info Emprunt");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ExemplaireID");

        empruntid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        emprunter.setBackground(new java.awt.Color(0, 0, 0));
        emprunter.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        emprunter.setForeground(new java.awt.Color(255, 255, 255));
        emprunter.setText("Creér Emprunt");
        emprunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprunterActionPerformed(evt);
            }
        });

        vd.setBackground(new java.awt.Color(0, 0, 0));
        vd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vd.setForeground(new java.awt.Color(255, 255, 255));
        vd.setText("Vider Les Champs");
        vd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdActionPerformed(evt);
            }
        });

        Blist12.setBackground(new java.awt.Color(0, 0, 0));
        Blist12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist12.setForeground(new java.awt.Color(255, 255, 255));
        Blist12.setText("Lister Tout");
        Blist12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blist12ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DateEmprunt");

        exmpid.setEditable(false);
        exmpid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        vidertableau.setBackground(new java.awt.Color(0, 0, 0));
        vidertableau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vidertableau.setForeground(new java.awt.Color(255, 255, 255));
        vidertableau.setText("Vider Le Tableau");
        vidertableau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidertableauActionPerformed(evt);
            }
        });

        chemp.setBackground(new java.awt.Color(0, 0, 0));
        chemp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        chemp.setForeground(new java.awt.Color(255, 255, 255));
        chemp.setText("Chercher Par Date");
        chemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chempActionPerformed(evt);
            }
        });

        rendreemp.setBackground(new java.awt.Color(0, 0, 0));
        rendreemp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        rendreemp.setForeground(new java.awt.Color(255, 255, 255));
        rendreemp.setText("Rendre Emprunt");
        rendreemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendreempActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UsagerID");

        usID.setEditable(false);
        usID.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EmpruntID");

        cherID.setBackground(new java.awt.Color(0, 0, 0));
        cherID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cherID.setForeground(new java.awt.Color(255, 255, 255));
        cherID.setText("Chercher Par ID");
        cherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherIDActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DateRetourEffectif");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date2");

        chempintervale.setBackground(new java.awt.Color(0, 0, 0));
        chempintervale.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        chempintervale.setForeground(new java.awt.Color(255, 255, 255));
        chempintervale.setText("Chercher Par Intervale");
        chempintervale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chempintervaleActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RechDateEmprunt");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date1");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DateRetourPrevue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usID, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateempr, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateempprev, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateretour, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empruntid, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datereche, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vd, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidertableau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emprunter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Blist12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cherID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chemp, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(rendreemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chempintervale)
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exmpid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateempr, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateempprev, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateretour, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(vidertableau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emprunter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rendreemp)
                        .addGap(18, 18, 18)
                        .addComponent(Blist12)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(empruntid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cherID)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datereche, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(chemp)
                        .addGap(18, 18, 18)
                        .addComponent(chempintervale)))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        TableEmprunt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableEmprunt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableEmprunt.setForeground(new java.awt.Color(102, 102, 102));
        TableEmprunt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ExemplaireID", "UsagerID", "Date_Emprunt", "Date_Retour_Prevue", "Date_Retour_Effectif"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableEmprunt.setGridColor(new java.awt.Color(255, 255, 255));
        TableEmprunt.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableEmprunt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableEmpruntMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableEmprunt);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch.setText("Chercher Par Oeuvre");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identifier Exemplaire");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vider Le Tableau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboeuvre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comboeuvre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NoChoice" }));
        comboeuvre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboeuvreItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomForSearch)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboeuvre, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(comboeuvre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        TableExemplaire2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableExemplaire2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableExemplaire2.setForeground(new java.awt.Color(102, 102, 102));
        TableExemplaire2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "OeuvreID", "Etat"
            }
        ));
        TableExemplaire2.setGridColor(new java.awt.Color(255, 255, 255));
        TableExemplaire2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableExemplaire2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableExemplaire2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableExemplaire2);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch4.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch4.setText("Chercher Par Nom");

        Nomrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomrechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomrechKeyTyped(evt);
            }
        });

        Blist4.setBackground(new java.awt.Color(0, 0, 0));
        Blist4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist4.setForeground(new java.awt.Color(255, 255, 255));
        Blist4.setText("Lister Tout");
        Blist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blist4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Identifier Usager");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Vider Le Tableau");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomForSearch4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Blist4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nomrech, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomForSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nomrech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Blist4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableUsager.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableUsager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableUsager.setForeground(new java.awt.Color(102, 102, 102));
        TableUsager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Date_Naissance", "Tel", "Adresse"
            }
        ));
        TableUsager.setGridColor(new java.awt.Color(255, 255, 255));
        TableUsager.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableUsager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUsagerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableUsager);

        Menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bibal_yazid_saad/View/1492889707_go-home.png"))); // NOI18N
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(509, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void currentdateemp(){
    Calendar cal=new GregorianCalendar();
        int Year=cal.get(Calendar.YEAR);
    int Month=cal.get(Calendar.MONTH); 
    int Day=cal.get(Calendar.DAY_OF_MONTH);
   dateempr.setDate(java.sql.Date.valueOf(Year+"-"+Month+"-"+Day));
    
}
public void currentdaterteffective(){
    Calendar cal=new GregorianCalendar();
        int Year=cal.get(Calendar.YEAR);
    int Month=cal.get(Calendar.MONTH); 
    int Day=cal.get(Calendar.DAY_OF_MONTH);
   dateretour.setDate(java.sql.Date.valueOf(Year+"-"+Month+"-"+Day));
    
}

    private void emprunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprunterActionPerformed
        // TODO add your handling code here:
       
         if(exmpid.getText().equals("") || usID.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Remplir Tous Les Champs Avant Ajouter","Erreur",JOptionPane.ERROR_MESSAGE);
         }
         else{
             
        
                    
          
             
                      
             
               
         pc.emprunter(exmpid.getText(), usID.getText(), convertUtilDateToSqlDate(dateempr.getDate()), convertUtilDateToSqlDate(dateempprev.getDate()));
        JOptionPane.showMessageDialog(null, "Ajout Avec Succés","OK",JOptionPane.INFORMATION_MESSAGE);
        
        pc.Lister();
        TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
          viderr();
         
         
         
         }
         
    }//GEN-LAST:event_emprunterActionPerformed

    private void TableEmpruntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableEmpruntMouseClicked
        // TODO add your handling code here:
         try {
            int row=TableEmprunt.getSelectedRow();
            String Table_click=(TableEmprunt.getModel().getValueAt(row, 0).toString());
            
            
            pc.FindForJtable(Table_click);
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("ExemplaireID");
                exmpid.setText(add1);
                String add2=DbInteraction.rs.getString("UsagerID");
                usID.setText(add2);
                Date dateemp= DbInteraction.rs.getDate("Date_Emprunt");
                dateempr.setDate(dateemp);
                Date datepr= DbInteraction.rs.getDate("Date_Retour_Prevue");
                dateempprev.setDate(datepr);
                Date dateret= DbInteraction.rs.getDate("Date_Retour_Effectif");
                dateempprev.setDate(dateret);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_TableEmpruntMouseClicked
        public void videtable(){
            DefaultTableModel dm = (DefaultTableModel) TableExemplaire2.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }}}
            public void videtableex(){
            DefaultTableModel dm = (DefaultTableModel) TableEmprunt.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }
        

        } 
             public void videtableus(){
            DefaultTableModel dm = (DefaultTableModel) TableUsager.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }}public  void viderr(){
        exmpid.setText("");
        usID.setText("");
        empruntid.setText("");
        date1.setDate(null);
        date2.setDate(null);
        dateempprev.setDate(null);
        dateretour.setDate(null);
        
        
}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        currentdateemp();
            
        EmpruntManager em=new EmpruntManager();
        em.listeoeuvre();
        try {
            while ( DbInteraction.rs.next())
            {
                
                comboeuvre.addItem(DbInteraction.rs.getString("Titre")); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(IHMemprunt.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        videtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdActionPerformed
        // TODO add your handling code here:
        viderr();
    }//GEN-LAST:event_vdActionPerformed

    private void TableExemplaire2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableExemplaire2MouseClicked
        // TODO add your handling code here:
        
        try {
            int row=TableExemplaire2.getSelectedRow();
            String Table_click=(TableExemplaire2.getModel().getValueAt(row, 0).toString());
            
           ec.FindForJtable(Table_click);
            
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("ID");
                exmpid.setText(add1);
                
                 
                 
           
            
               
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
    }//GEN-LAST:event_TableExemplaire2MouseClicked

    private void Blist12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blist12ActionPerformed
        // TODO add your handling code here:
        pc.Lister();
        TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
                
    }//GEN-LAST:event_Blist12ActionPerformed

    private void vidertableauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidertableauActionPerformed
        // TODO add your handling code here:
        videtableex();
    }//GEN-LAST:event_vidertableauActionPerformed

    private void chempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chempActionPerformed
        // TODO add your handling code here:
      pc.findByDate(convertUtilDateToSqlDate(datereche.getDate()));
      TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));

      
    }//GEN-LAST:event_chempActionPerformed

    private void cherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherIDActionPerformed
        // TODO add your handling code here:
        if(empruntid.getText()!=null){
           pc.findById(Integer.parseInt(empruntid.getText()));
        TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        }
        
        if(exmpid.getText()!=null){
             pc.findByExemplaire(Integer.parseInt(exmpid.getText()));
        TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        }
        
        if(usID.getText()!=null){
             pc.findByUsager(Integer.parseInt(usID.getText()));
        TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        }
        
    }//GEN-LAST:event_cherIDActionPerformed

    private void NomrechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyReleased
        // TODO add your handling code here:

        uc.FindByName(Nomrech.getText());
        TableUsager.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        // if(Nomrech.getText().equals("")){
            //     videtable();
            // }

        if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){

            videtable();

        }

    }//GEN-LAST:event_NomrechKeyReleased

    private void NomrechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
        char c = evt.getKeyChar();
        //le caractère est numérique
        if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' ) {
            // System.out.println(evt);
        } else {
            //suppression du caractère
            evt.consume();
        }

    }//GEN-LAST:event_NomrechKeyTyped

    private void Blist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blist4ActionPerformed
        // TODO add your handling code here:

        uc.Lister();
        TableUsager.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_Blist4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       videtableus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TableUsagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsagerMouseClicked
        // TODO add your handling code here:
        try {
            int row=TableUsager.getSelectedRow();
            String Table_click=(TableUsager.getModel().getValueAt(row, 0).toString());

           uc.FindForJtable(Table_click);

            if(DbInteraction.rs.next()){

                String add1=DbInteraction.rs.getString("ID");
                usID.setText(add1);
                

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_TableUsagerMouseClicked

    private void rendreempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendreempActionPerformed
        // TODO add your handling code here:
       currentdaterteffective();
         int row=IHMemprunt.TableEmprunt.getSelectedRow();
         String idp=(TableEmprunt.getModel().getValueAt(row, 0).toString());
         pc.rendre(convertUtilDateToSqlDate(dateretour.getDate()),Integer.parseInt(idp));
         JOptionPane.showMessageDialog(null, "Date Retour Effectif Remplis");
         viderr();
         pc.Lister();
         TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        
    }//GEN-LAST:event_rendreempActionPerformed

    private void chempintervaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chempintervaleActionPerformed
        // TODO add your handling code here:
        pc.findByIntervalDate(convertUtilDateToSqlDate(date1.getDate()), convertUtilDateToSqlDate(date2.getDate()));
         TableEmprunt.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_chempintervaleActionPerformed

    private void comboeuvreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboeuvreItemStateChanged
        // TODO add your handling code here:
         ec.FindByOeuvre(comboeuvre.getSelectedItem().toString());
        TableExemplaire2.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_comboeuvreItemStateChanged

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu menu=new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMemprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMemprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMemprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMemprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMemprunt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blist12;
    private javax.swing.JButton Blist4;
    private javax.swing.JButton Menu;
    private javax.swing.JLabel NomForSearch;
    private javax.swing.JLabel NomForSearch4;
    private javax.swing.JTextField Nomrech;
    private static javax.swing.JTable TableEmprunt;
    private javax.swing.JTable TableExemplaire2;
    private static javax.swing.JTable TableUsager;
    private javax.swing.JButton chemp;
    private javax.swing.JButton chempintervale;
    private javax.swing.JButton cherID;
    private javax.swing.JComboBox<String> comboeuvre;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private com.toedter.calendar.JDateChooser dateempprev;
    private com.toedter.calendar.JDateChooser dateempr;
    private com.toedter.calendar.JDateChooser datereche;
    private com.toedter.calendar.JDateChooser dateretour;
    private javax.swing.JButton emprunter;
    private javax.swing.JTextField empruntid;
    private javax.swing.JTextField exmpid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton rendreemp;
    private javax.swing.JTextField usID;
    private javax.swing.JButton vd;
    private javax.swing.JButton vidertableau;
    // End of variables declaration//GEN-END:variables

  public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
   
      
      
      
      if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Enter Une Date D'Emprunt","Erreur",JOptionPane.ERROR_MESSAGE);
        JOptionPane.showMessageDialog(null,"Enter Une Date De Retour Prevue","Erreur",JOptionPane.ERROR_MESSAGE);

    }
    return null;
}
   
}
