/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibal_yazid_saad.View;

import bibal_yazid_saad.Connection.DbInteraction;
import bibal_yazid_saad.Controller.ExemplaireControler;
import bibal_yazid_saad.Controller.OeuvreControler;
import bibal_yazid_saad.Controller.ReservationControler;
import bibal_yazid_saad.Controller.UsagerControler;
import bibal_yazid_saad.Model.Oeuvre;
import static bibal_yazid_saad.View.IHMusager.convertUtilDateToSqlDate;

import com.mysql.jdbc.PreparedStatement;
import com.sun.org.apache.xerces.internal.impl.dv.xs.DateTimeDV;
import java.sql.ResultSet;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

//import net.proteanit.sql.DbUtils;


/**
 *
 * @author dizay
 */
public class IHMreservation extends javax.swing.JFrame {

    /**
     * Creates new form IHMusager
     */
    OeuvreControler  oc=new OeuvreControler(); 
    ExemplaireControler ec=new ExemplaireControler();
    UsagerControler uc=new UsagerControler();
    ReservationControler rc=new ReservationControler();
       
    public IHMreservation() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reserID = new javax.swing.JTextField();
        reserver = new javax.swing.JButton();
        vd = new javax.swing.JButton();
        Blist12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        oeid = new javax.swing.JTextField();
        vidertableau = new javax.swing.JButton();
        chexp = new javax.swing.JButton();
        etatres = new javax.swing.JComboBox<>();
        annuler = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        usID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cherID = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableReservation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        NomForSearch = new javax.swing.JLabel();
        Titrech = new javax.swing.JTextField();
        Blist = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableOeuvre2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        NomForSearch4 = new javax.swing.JLabel();
        Nomrech3 = new javax.swing.JTextField();
        Blist4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableUsager = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Info Reservation");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OeuvreID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Etat");

        reserID.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        reserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reserIDKeyTyped(evt);
            }
        });

        reserver.setBackground(new java.awt.Color(0, 0, 0));
        reserver.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reserver.setForeground(new java.awt.Color(255, 255, 255));
        reserver.setText("Creér Reservation");
        reserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserverActionPerformed(evt);
            }
        });
        reserver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reserverKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reserverKeyReleased(evt);
            }
        });

        vd.setBackground(new java.awt.Color(0, 0, 0));
        vd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vd.setForeground(new java.awt.Color(255, 255, 255));
        vd.setText("Vider Les Champs");
        vd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdActionPerformed(evt);
            }
        });

        Blist12.setBackground(new java.awt.Color(0, 0, 0));
        Blist12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist12.setForeground(new java.awt.Color(255, 255, 255));
        Blist12.setText("Lister Tout");
        Blist12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blist12ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DateResa");

        oeid.setEditable(false);
        oeid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        oeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                oeidKeyTyped(evt);
            }
        });

        vidertableau.setBackground(new java.awt.Color(0, 0, 0));
        vidertableau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vidertableau.setForeground(new java.awt.Color(255, 255, 255));
        vidertableau.setText("Vider Le Tableau");
        vidertableau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidertableauActionPerformed(evt);
            }
        });

        chexp.setBackground(new java.awt.Color(0, 0, 0));
        chexp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        chexp.setForeground(new java.awt.Color(255, 255, 255));
        chexp.setText("Chercher Par Date");
        chexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chexpActionPerformed(evt);
            }
        });
        chexp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chexpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chexpKeyReleased(evt);
            }
        });

        etatres.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        etatres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NoChoice", "Reservé", "NonReservé", "Annulé", " " }));

        annuler.setBackground(new java.awt.Color(0, 0, 0));
        annuler.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Annuler Reservation");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UsagerID");

        usID.setEditable(false);
        usID.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        usID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usIDKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ReservationID");

        cherID.setBackground(new java.awt.Color(0, 0, 0));
        cherID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cherID.setForeground(new java.awt.Color(255, 255, 255));
        cherID.setText("Chercher Par ID");
        cherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherIDActionPerformed(evt);
            }
        });
        cherID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cherIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cherIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etatres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usID)
                                .addComponent(oeid, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(reserID))))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Blist12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vd, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidertableau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cherID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oeid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vd))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(usID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(etatres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(vidertableau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reserver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(annuler)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cherID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reserID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Blist12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(chexp)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
        );

        TableReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableReservation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableReservation.setForeground(new java.awt.Color(102, 102, 102));
        TableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "OeuvreID", "UsagerID", "DateReservation", "Etat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableReservation.setGridColor(new java.awt.Color(255, 255, 255));
        TableReservation.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReservationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableReservation);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch.setText("Chercher Par Titre");

        Titrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TitrechKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TitrechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TitrechKeyTyped(evt);
            }
        });

        Blist.setBackground(new java.awt.Color(0, 0, 0));
        Blist.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist.setForeground(new java.awt.Color(255, 255, 255));
        Blist.setText("Lister Tout");
        Blist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlistActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identifier Oeuvre");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vider Le Tableau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomForSearch)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Blist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(Titrech, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titrech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Blist))
                .addGap(23, 23, 23))
        );

        TableOeuvre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableOeuvre2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableOeuvre2.setForeground(new java.awt.Color(102, 102, 102));
        TableOeuvre2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titre", "Auteur", "NbrReservation", "Lending", "Lending2", "Type"
            }
        ));
        TableOeuvre2.setGridColor(new java.awt.Color(255, 255, 255));
        TableOeuvre2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableOeuvre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableOeuvre2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableOeuvre2);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch4.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch4.setText("Chercher Par Nom");

        Nomrech3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nomrech3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Nomrech3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Nomrech3KeyTyped(evt);
            }
        });

        Blist4.setBackground(new java.awt.Color(0, 0, 0));
        Blist4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist4.setForeground(new java.awt.Color(255, 255, 255));
        Blist4.setText("Lister Tout");
        Blist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blist4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Identifier Usager");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Vider Le Tableau");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomForSearch4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Blist4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nomrech3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomForSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nomrech3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Blist4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableUsager.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableUsager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableUsager.setForeground(new java.awt.Color(102, 102, 102));
        TableUsager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Date_Naissance", "Tel", "Adresse"
            }
        ));
        TableUsager.setGridColor(new java.awt.Color(255, 255, 255));
        TableUsager.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableUsager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUsagerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableUsager);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(670, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public static LocalDate convertToEntityAttribute(java.sql.Date date) {
    return date.toLocalDate();
  }
    private void reserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserverActionPerformed
        // TODO add your handling code here:
       
         if(oeid.getText().equals("") || etatres.getSelectedItem().equals("NoChoice")|| usID.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Remplir Tous Les Champs Avant Ajouter","Erreur",JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Choisir Un Etat De Reservation","Erreur",JOptionPane.ERROR_MESSAGE);
         }
         else{
             
        
             
    
   
              
        rc.reserver(oeid.getText(), usID.getText(),convertToEntityAttribute(Date.valueOf(LocalDate.now())),etatres.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null, "Ajout Avec Succés","OK",JOptionPane.INFORMATION_MESSAGE);
        
        rc.Lister();
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
          viderr();
         
         
         
         }
         
    }//GEN-LAST:event_reserverActionPerformed

    private void BlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlistActionPerformed
        // TODO add your handling code here:
        
        oc.Lister();
      TableOeuvre2.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_BlistActionPerformed

    private void TableReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReservationMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TableReservationMouseClicked
        public void videtable(){
            DefaultTableModel dm = (DefaultTableModel) TableOeuvre2.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }}}
            public void videtableex(){
            DefaultTableModel dm = (DefaultTableModel) TableReservation.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }

        }  
    private void TitrechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyReleased
        // TODO add your handling code here:
        
        
        oc.FindByTitle(Titrech.getText());
        TableOeuvre2.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        
        
        // if(Nomrech.getText().equals("")){
        //     videtable();
        // }
       
   
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){
         
                videtable();
            
    }
         
    }//GEN-LAST:event_TitrechKeyReleased
public  void viderr(){
        reserID.setText("");
        etatres.setSelectedItem("");
        
}
    private void reserIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reserIDKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reserIDKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
          
            
    
    }//GEN-LAST:event_formWindowActivated

    private void TitrechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
          char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z'|| c == KeyEvent.VK_SPACE) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
              
                
              
    }//GEN-LAST:event_TitrechKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        videtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdActionPerformed
        // TODO add your handling code here:
        viderr();
    }//GEN-LAST:event_vdActionPerformed

    private void TitrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TitrechKeyPressed

    private void reserverKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reserverKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reserverKeyReleased

    private void reserverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reserverKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reserverKeyPressed

    private void TableOeuvre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableOeuvre2MouseClicked
        // TODO add your handling code here:
        
        try {
            int row=TableOeuvre2.getSelectedRow();
            String Table_click=(TableOeuvre2.getModel().getValueAt(row, 0).toString());
            
             String sql="select * from oeuvre where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);
            
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("ID");
                oeid.setText(add1);
                
                 
                 
           
            
               
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
    }//GEN-LAST:event_TableOeuvre2MouseClicked

    private void Blist12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blist12ActionPerformed
        // TODO add your handling code here:
        ec.Lister();
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
                
    }//GEN-LAST:event_Blist12ActionPerformed

    private void oeidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oeidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_oeidKeyTyped

    private void vidertableauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidertableauActionPerformed
        // TODO add your handling code here:
        videtableex();
    }//GEN-LAST:event_vidertableauActionPerformed

    private void chexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chexpActionPerformed
        // TODO add your handling code here:
          ec.FindByOeuvre(reserID.getText());
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_chexpActionPerformed

    private void chexpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chexpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chexpKeyPressed

    private void chexpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chexpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chexpKeyReleased

    private void usIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usIDKeyTyped

    private void cherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cherIDActionPerformed

    private void cherIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cherIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cherIDKeyPressed

    private void cherIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cherIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cherIDKeyReleased

    private void Nomrech3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nomrech3KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_Nomrech3KeyPressed

    private void Nomrech3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nomrech3KeyReleased
        // TODO add your handling code here:

        uc.FindByName(Nomrech.getText());
        TableUsager.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        // if(Nomrech.getText().equals("")){
            //     videtable();
            // }

        if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){

            videtable();

        }

    }//GEN-LAST:event_Nomrech3KeyReleased

    private void Nomrech3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nomrech3KeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
        char c = evt.getKeyChar();
        //le caractère est numérique
        if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' ) {
            // System.out.println(evt);
        } else {
            //suppression du caractère
            evt.consume();
        }

    }//GEN-LAST:event_Nomrech3KeyTyped

    private void Blist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blist4ActionPerformed
        // TODO add your handling code here:

        uc.Lister();
        TableUsager.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_Blist4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        videtable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TableUsagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsagerMouseClicked
        // TODO add your handling code here:
        try {
            int row=TableUsager.getSelectedRow();
            String Table_click=(TableUsager.getModel().getValueAt(row, 0).toString());

            String sql="select * from usager where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);

            if(DbInteraction.rs.next()){

                String add1=DbInteraction.rs.getString("ID");
                usID.setText(add1);
                

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_TableUsagerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMreservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blist;
    private javax.swing.JButton Blist1;
    private javax.swing.JButton Blist12;
    private javax.swing.JButton Blist2;
    private javax.swing.JButton Blist3;
    private javax.swing.JButton Blist4;
    private javax.swing.JLabel NomForSearch;
    private javax.swing.JLabel NomForSearch1;
    private javax.swing.JLabel NomForSearch2;
    private javax.swing.JLabel NomForSearch3;
    private javax.swing.JLabel NomForSearch4;
    private javax.swing.JTextField Nomrech;
    private javax.swing.JTextField Nomrech1;
    private javax.swing.JTextField Nomrech2;
    private javax.swing.JTextField Nomrech3;
    private javax.swing.JTable TableOeuvre2;
    private static javax.swing.JTable TableReservation;
    private static javax.swing.JTable TableUsager;
    private javax.swing.JTextField Titrech;
    private javax.swing.JButton annuler;
    private javax.swing.JButton cherID;
    private javax.swing.JButton chexp;
    private javax.swing.JComboBox<String> etatres;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField oeid;
    private javax.swing.JTextField reserID;
    private javax.swing.JButton reserver;
    private javax.swing.JTextField usID;
    private javax.swing.JButton vd;
    private javax.swing.JButton vidertableau;
    // End of variables declaration//GEN-END:variables

  public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
   
      
      
      
      if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Enter Une Date De Reservation","Erreur",JOptionPane.ERROR_MESSAGE);
    }
    return null;
}
}
