/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibal_yazid_saad.View;

import bibal_yazid_saad.Connection.DbInteraction;
import bibal_yazid_saad.Controller.ExemplaireControler;
import bibal_yazid_saad.Controller.OeuvreControler;
import bibal_yazid_saad.Controller.ReservationControler;
import bibal_yazid_saad.Controller.UsagerControler;
import static bibal_yazid_saad.View.IHMusager.convertUtilDateToSqlDate;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author dizay
 */
public class IHMreservation extends javax.swing.JFrame {

    /**
     * Creates new form IHMusager
     */
    OeuvreControler  oc=new OeuvreControler(); 
    ExemplaireControler ec=new ExemplaireControler();
    UsagerControler uc=new UsagerControler();
    ReservationControler rc=new ReservationControler();
       
    public IHMreservation() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reserID = new javax.swing.JTextField();
        reserver = new javax.swing.JButton();
        vd = new javax.swing.JButton();
        Blist12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        oeid = new javax.swing.JTextField();
        vidertableau = new javax.swing.JButton();
        chexp = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        usID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cherID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        etatresa = new javax.swing.JComboBox<>();
        dateress = new com.toedter.calendar.JDateChooser();
        dateann = new com.toedter.calendar.JDateChooser();
        daterecherche = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        date1 = new com.toedter.calendar.JDateChooser();
        chexpintervale = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableReservation = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        NomForSearch = new javax.swing.JLabel();
        Titrech = new javax.swing.JTextField();
        Blist = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableOeuvre2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        NomForSearch4 = new javax.swing.JLabel();
        Nomrech = new javax.swing.JTextField();
        Blist4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableUsager = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nbrResa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Info Reservation");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OeuvreID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Etat");

        reserID.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        reserID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reserIDKeyTyped(evt);
            }
        });

        reserver.setBackground(new java.awt.Color(0, 0, 0));
        reserver.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reserver.setForeground(new java.awt.Color(255, 255, 255));
        reserver.setText("Creér Reservation");
        reserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserverActionPerformed(evt);
            }
        });
        reserver.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                reserverKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reserverKeyReleased(evt);
            }
        });

        vd.setBackground(new java.awt.Color(0, 0, 0));
        vd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vd.setForeground(new java.awt.Color(255, 255, 255));
        vd.setText("Vider Les Champs");
        vd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdActionPerformed(evt);
            }
        });

        Blist12.setBackground(new java.awt.Color(0, 0, 0));
        Blist12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist12.setForeground(new java.awt.Color(255, 255, 255));
        Blist12.setText("Lister Tout");
        Blist12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blist12ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DateResa");

        oeid.setEditable(false);
        oeid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        oeid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                oeidKeyTyped(evt);
            }
        });

        vidertableau.setBackground(new java.awt.Color(0, 0, 0));
        vidertableau.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vidertableau.setForeground(new java.awt.Color(255, 255, 255));
        vidertableau.setText("Vider Le Tableau");
        vidertableau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vidertableauActionPerformed(evt);
            }
        });

        chexp.setBackground(new java.awt.Color(0, 0, 0));
        chexp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        chexp.setForeground(new java.awt.Color(255, 255, 255));
        chexp.setText("Chercher Par Date");
        chexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chexpActionPerformed(evt);
            }
        });
        chexp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chexpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chexpKeyReleased(evt);
            }
        });

        annuler.setBackground(new java.awt.Color(0, 0, 0));
        annuler.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Annuler Reservation");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("UsagerID");

        usID.setEditable(false);
        usID.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        usID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usIDKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ReservationID");

        cherID.setBackground(new java.awt.Color(0, 0, 0));
        cherID.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cherID.setForeground(new java.awt.Color(255, 255, 255));
        cherID.setText("Chercher Par ID");
        cherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherIDActionPerformed(evt);
            }
        });
        cherID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cherIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cherIDKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DateAnn");

        etatresa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        etatresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NoChoice", "Réservé", "NonRéservé" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date2");

        chexpintervale.setBackground(new java.awt.Color(0, 0, 0));
        chexpintervale.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        chexpintervale.setForeground(new java.awt.Color(255, 255, 255));
        chexpintervale.setText("Chercher Par Intervale");
        chexpintervale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chexpintervaleActionPerformed(evt);
            }
        });
        chexpintervale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chexpintervaleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                chexpintervaleKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RechDateResa");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateann, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usID)
                                    .addComponent(oeid)
                                    .addComponent(etatresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addComponent(daterecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reserID)
                                .addComponent(date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Blist12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(annuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vd, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidertableau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cherID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chexp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chexpintervale)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oeid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vd)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(etatresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(vidertableau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reserver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annuler)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Blist12)
                        .addGap(33, 33, 33)
                        .addComponent(cherID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateann, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(reserID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(daterecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chexp))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(chexpintervale)
                        .addGap(52, 52, 52))))
        );

        TableReservation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableReservation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableReservation.setForeground(new java.awt.Color(102, 102, 102));
        TableReservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "OeuvreID", "UsagerID", "DateReservation", "DateAnnulation", "Etat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableReservation.setGridColor(new java.awt.Color(255, 255, 255));
        TableReservation.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableReservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReservationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableReservation);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch.setText("Chercher Par Titre");

        Titrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TitrechKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TitrechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TitrechKeyTyped(evt);
            }
        });

        Blist.setBackground(new java.awt.Color(0, 0, 0));
        Blist.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist.setForeground(new java.awt.Color(255, 255, 255));
        Blist.setText("Lister Tout");
        Blist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlistActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identifier Oeuvre");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Vider Le Tableau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomForSearch)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Blist)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(Titrech, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titrech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Blist))
                .addGap(23, 23, 23))
        );

        TableOeuvre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableOeuvre2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableOeuvre2.setForeground(new java.awt.Color(102, 102, 102));
        TableOeuvre2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titre", "Auteur", "NbrReservation", "Lending", "Lending2", "Type"
            }
        ));
        TableOeuvre2.setGridColor(new java.awt.Color(255, 255, 255));
        TableOeuvre2.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableOeuvre2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableOeuvre2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableOeuvre2);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        NomForSearch4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NomForSearch4.setForeground(new java.awt.Color(255, 255, 255));
        NomForSearch4.setText("Chercher Par Nom");

        Nomrech.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomrechKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NomrechKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomrechKeyTyped(evt);
            }
        });

        Blist4.setBackground(new java.awt.Color(0, 0, 0));
        Blist4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Blist4.setForeground(new java.awt.Color(255, 255, 255));
        Blist4.setText("Lister Tout");
        Blist4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blist4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Identifier Usager");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Vider Le Tableau");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomForSearch4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Blist4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Nomrech, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomForSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nomrech, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Blist4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableUsager.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TableUsager.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TableUsager.setForeground(new java.awt.Color(102, 102, 102));
        TableUsager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Date_Naissance", "Tel", "Adresse"
            }
        ));
        TableUsager.setGridColor(new java.awt.Color(255, 255, 255));
        TableUsager.setSelectionBackground(new java.awt.Color(0, 0, 0));
        TableUsager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUsagerMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TableUsager);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre de reservation");

        nbrResa.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(nbrResa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nbrResa))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void currentdatere(){
    Calendar cal=new GregorianCalendar();
        int Year=cal.get(Calendar.YEAR);
    int Month=cal.get(Calendar.MONTH); 
    int Day=cal.get(Calendar.DAY_OF_MONTH);
   dateress.setDate(java.sql.Date.valueOf(Year+"-"+Month+"-"+Day));
    
}
public void currentdateann(){
    Calendar cal=new GregorianCalendar();
        int Year=cal.get(Calendar.YEAR);
    int Month=cal.get(Calendar.MONTH); 
    int Day=cal.get(Calendar.DAY_OF_MONTH);
   dateann.setDate(java.sql.Date.valueOf(Year+"-"+Month+"-"+Day));
    
}
    private void reserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserverActionPerformed
        // TODO add your handling code here:
       
         if(oeid.getText().equals("") || etatresa.getSelectedItem()=="NoChoice"|| usID.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Remplir Tous Les Champs Avant Ajouter","Erreur",JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(null, "Choisir Un Etat De Reservation","Erreur",JOptionPane.ERROR_MESSAGE);
         }
         else{
             
        
                    
          
             
                      
             
               
             
        rc.reserver(Integer.parseInt(oeid.getText()), Integer.parseInt(usID.getText()), convertUtilDateToSqlDate(dateress.getDate()), etatresa.getSelectedItem().toString());
        oc.nbrReservation();
        JOptionPane.showMessageDialog(null, "Ajout Avec Succés","OK",JOptionPane.INFORMATION_MESSAGE);
        
        rc.Lister();
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
          viderr();
         
         
         
         }
         
    }//GEN-LAST:event_reserverActionPerformed

    private void BlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlistActionPerformed
        // TODO add your handling code here:
        
        oc.Lister();
      TableOeuvre2.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_BlistActionPerformed

    private void TableReservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReservationMouseClicked
        // TODO add your handling code here:
         try {
            int row=TableReservation.getSelectedRow();
            String Table_click=(TableReservation.getModel().getValueAt(row, 0).toString());
            
             String sql="select * from reservation where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);
            
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("OeuvreID");
                oeid.setText(add1);
                String add2=DbInteraction.rs.getString("UsagerID");
                usID.setText(add2);
                Date dater= DbInteraction.rs.getDate("DateReservation");
                dateress.setDate(dater);
                Date datea= DbInteraction.rs.getDate("DateAnnulation");
                dateann.setDate(datea);
                String et=DbInteraction.rs.getString("Etat");
                etatresa.setSelectedItem(et);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_TableReservationMouseClicked
        public void videtable(){
            DefaultTableModel dm = (DefaultTableModel) TableOeuvre2.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }}}
            public void videtableex(){
            DefaultTableModel dm = (DefaultTableModel) TableReservation.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }
        

        } 
             public void videtableus(){
            DefaultTableModel dm = (DefaultTableModel) TableUsager.getModel();

        while(dm.getRowCount()>0){
            for(int i=0;i<dm.getRowCount();i++){
                dm.removeRow(i);
            }
            
    }}
    private void TitrechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyReleased
        // TODO add your handling code here:
        
        
        oc.FindByTitle(Titrech.getText());
        TableOeuvre2.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        
        
        // if(Nomrech.getText().equals("")){
        //     videtable();
        // }
       
   
    if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){
         
                videtable();
            
    }
         
    }//GEN-LAST:event_TitrechKeyReleased
public  void viderr(){
        oeid.setText("");
        usID.setText("");
        etatresa.setSelectedItem("");
        daterecherche.setDate(null);
        reserID.setText("");
        date1.setDate(null);
        date2.setDate(null);
        
        
}
    private void reserIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reserIDKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reserIDKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        currentdatere();
      
    }//GEN-LAST:event_formWindowActivated

    private void TitrechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
          char c = evt.getKeyChar();
                //le caractère est numérique
                if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z'|| c == KeyEvent.VK_SPACE) {
                    // System.out.println(evt);
                } else {
                    //suppression du caractère
                    evt.consume();
                }
              
                
              
    }//GEN-LAST:event_TitrechKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        videtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdActionPerformed
        // TODO add your handling code here:
        viderr();
    }//GEN-LAST:event_vdActionPerformed

    private void TitrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitrechKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TitrechKeyPressed

    private void reserverKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reserverKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reserverKeyReleased

    private void reserverKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reserverKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_reserverKeyPressed

    private void TableOeuvre2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableOeuvre2MouseClicked
        // TODO add your handling code here:
        
        try {
            int row=TableOeuvre2.getSelectedRow();
            String Table_click=(TableOeuvre2.getModel().getValueAt(row, 0).toString());
            
             String sql="select * from oeuvre where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);
            
            if(DbInteraction.rs.next()){
                
                
                String add1=DbInteraction.rs.getString("ID");
                oeid.setText(add1);
                
                 
                 
           
            
               
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
       
    }//GEN-LAST:event_TableOeuvre2MouseClicked

    private void Blist12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blist12ActionPerformed
        // TODO add your handling code here:
        rc.Lister();
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));  
        int nbr=TableReservation.getRowCount();
        nbrResa.setText(String.valueOf(nbr));
        
        
                
    }//GEN-LAST:event_Blist12ActionPerformed

    private void oeidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oeidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_oeidKeyTyped

    private void vidertableauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vidertableauActionPerformed
        // TODO add your handling code here:
        videtableex();
    }//GEN-LAST:event_vidertableauActionPerformed

    private void chexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chexpActionPerformed
        // TODO add your handling code here:
      rc.findByDate(convertUtilDateToSqlDate(daterecherche.getDate()));
      TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));

      
    }//GEN-LAST:event_chexpActionPerformed

    private void chexpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chexpKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chexpKeyPressed

    private void chexpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chexpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chexpKeyReleased

    private void usIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usIDKeyTyped

    private void cherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherIDActionPerformed
        // TODO add your handling code here:
        if(reserID.getText()!=null){
           rc.findById(Integer.parseInt(reserID.getText()));
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        }
        
        if(oeid.getText()!=null){
             rc.findByOeuvre(Integer.parseInt(oeid.getText()));
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        }
        
        if(oeid.getText()!=null){
             rc.findByUsager(Integer.parseInt(usID.getText()));
        TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        }
        
    }//GEN-LAST:event_cherIDActionPerformed

    private void cherIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cherIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cherIDKeyPressed

    private void cherIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cherIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cherIDKeyReleased

    private void NomrechKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_NomrechKeyPressed

    private void NomrechKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyReleased
        // TODO add your handling code here:

        uc.FindByName(Nomrech.getText());
        TableUsager.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        // if(Nomrech.getText().equals("")){
            //     videtable();
            // }

        if( evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){

            videtable();

        }

    }//GEN-LAST:event_NomrechKeyReleased

    private void NomrechKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomrechKeyTyped
        // TODO add your handling code here:char c = evt.getKeyChar();
        char c = evt.getKeyChar();
        //le caractère est numérique
        if (c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z' ) {
            // System.out.println(evt);
        } else {
            //suppression du caractère
            evt.consume();
        }

    }//GEN-LAST:event_NomrechKeyTyped

    private void Blist4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blist4ActionPerformed
        // TODO add your handling code here:

        uc.Lister();
        TableUsager.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_Blist4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       videtableus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TableUsagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUsagerMouseClicked
        // TODO add your handling code here:
        try {
            int row=TableUsager.getSelectedRow();
            String Table_click=(TableUsager.getModel().getValueAt(row, 0).toString());

            String sql="select * from usager where ID='"+Table_click+"' ";
            DbInteraction.pst=(PreparedStatement) DbInteraction.con.prepareStatement(sql);
            DbInteraction.rs=(com.mysql.jdbc.ResultSet) (ResultSet) DbInteraction.pst.executeQuery(sql);

            if(DbInteraction.rs.next()){

                String add1=DbInteraction.rs.getString("ID");
                usID.setText(add1);
                

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_TableUsagerMouseClicked

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        // TODO add your handling code here:
       currentdateann();
         int row=IHMreservation.TableReservation.getSelectedRow();
        String idr=(TableReservation.getModel().getValueAt(row, 0).toString());
        rc.annuler(convertUtilDateToSqlDate(dateann.getDate()), etatresa.getSelectedItem().toString(), Integer.parseInt(idr));
        
         JOptionPane.showMessageDialog(null, "Annulation de la Reservation passe Avec Succés");
         viderr();
         rc.Lister();
         TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
        
    }//GEN-LAST:event_annulerActionPerformed

    private void chexpintervaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chexpintervaleActionPerformed
        // TODO add your handling code here:
        rc.findByIntervalDate(convertUtilDateToSqlDate(date1.getDate()), convertUtilDateToSqlDate(date2.getDate()));
         TableReservation.setModel(DbUtils.resultSetToTableModel(DbInteraction.rs));
    }//GEN-LAST:event_chexpintervaleActionPerformed

    private void chexpintervaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chexpintervaleKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_chexpintervaleKeyPressed

    private void chexpintervaleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chexpintervaleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_chexpintervaleKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMreservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHMreservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blist;
    private javax.swing.JButton Blist12;
    private javax.swing.JButton Blist4;
    private javax.swing.JLabel NomForSearch;
    private javax.swing.JLabel NomForSearch4;
    private javax.swing.JTextField Nomrech;
    private javax.swing.JTable TableOeuvre2;
    private static javax.swing.JTable TableReservation;
    private static javax.swing.JTable TableUsager;
    private javax.swing.JTextField Titrech;
    private javax.swing.JButton annuler;
    private javax.swing.JButton cherID;
    private javax.swing.JButton chexp;
    private javax.swing.JButton chexpintervale;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private com.toedter.calendar.JDateChooser dateann;
    private com.toedter.calendar.JDateChooser daterecherche;
    private com.toedter.calendar.JDateChooser dateress;
    private javax.swing.JComboBox<String> etatresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nbrResa;
    private javax.swing.JTextField oeid;
    private javax.swing.JTextField reserID;
    private javax.swing.JButton reserver;
    private javax.swing.JTextField usID;
    private javax.swing.JButton vd;
    private javax.swing.JButton vidertableau;
    // End of variables declaration//GEN-END:variables

  public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
   
      
      
      
      if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
    else
    {
       JOptionPane.showMessageDialog(null,"Enter Une Date De Reservation","Erreur",JOptionPane.ERROR_MESSAGE);
    }
    return null;
}
   
}
